version: '3.8'

services:
  portfolio-website:
    image: portfolio-website:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
